name: tea-alert-device

version: 0.0.1

volumes:
  node_modules:
  data:


services:
  sensor:
    image: sensor
    env_file:
      - .env
    build:
      context: ./sensor
    volumes:
      - ./sensor:/app
      - data:/data

  login:
    image: login
    build:
      context: ./login
    volumes:
      - ./login:/app
      - data:/data
      - node_modules:/app/node_modules
    ports:
      - 80:80
